# Generated by Django 5.2.8 on 2025-11-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='is_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
