# Generated by Django 5.2.8 on 2025-11-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userconfirmation_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfirmation',
            name='is_expired',
        ),
    ]
