# Generated by Django 5.2.8 on 2025-11-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userconfirmation_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
