# Generated by Django 5.2.8 on 2025-11-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_changeuserspassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeuserspassword',
            old_name='token',
            new_name='access_token',
        ),
    ]
